### ISSUE TITLE
is it possible to reduce the size of the ID at the expense of less ULIDs per millisecond?

### ISSUE THREAD

**Issue by jsmedmar** [ahawker/ulid#322]
Wondering if its possible to reduce the size of the ID at the expense of less ULIDs per millisecond?

**Comment by ahawker** [comment]
I'm assuming you mean less than 128 bits? Changing that would break the [spec](https://github.com/ulid/spec). However, in a general sense, yes you could create identifier values that require less space by storing less time information, say at a second granularity instead of a millisecond like ulid specifies. However, that would be a separate implementation is out of scope for this library.
